# Db Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.db.name }}
spec:
  serviceName: {{ .Values.db.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: {{ .Values.db.name }}
        image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
        imagePullPolicy: {{ .Values.db.image.pullPolicy }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.environment.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.environment.POSTGRES_PASSWORD }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            cpu: {{ .Values.db.resources.limits.cpu }}
            memory: {{ .Values.db.resources.limits.memory }}
          requests:
            cpu: {{ .Values.db.resources.requests.cpu }}
            memory: {{ .Values.db.resources.requests.memory }}
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp2
      resources:
        requests:
          storage: 1Gi