apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.db.name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: voting-app
type: Opaque
data:
  username: {{ .Values.db.environment.POSTGRES_USER | b64enc }}
  password: {{ .Values.db.environment.POSTGRES_PASSWORD | b64enc }}